# Generated by Django 2.2.10 on 2020-10-09 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=20)),
                ('category_clothes', models.CharField(choices=[('Shirt', 'Shirt'), ('Tshirt', 'Tshirt'), ('Pants', 'Pants'), ('Manto', 'Manto'), ('Blouse', 'Blouse')], default='Shirt', max_length=20)),
                ('size_this', models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Huawei', 'Huawei'), ('ASUS', 'ASUS'), ('Samsung', 'Samsung'), ('Apple', 'Apple')], default='Huawei', max_length=20)),
                ('weight', models.FloatField()),
                ('category_elec', models.CharField(choices=[('LapTop', 'LapTop'), ('Mobile', 'Mobile'), ('Headset', 'Headset'), ('Charger', 'Charger')], default='LapTop', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('real_price', models.IntegerField(default=0)),
                ('num', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.FloatField(default=0)),
                ('score_num', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Electronic', 'Electronic'), ('Clothes', 'Clothes'), ('HomeAppliances', 'HomeAppliances'), ('Sport', 'Sport'), ('Stationery', 'Stationery')], default='Electronic', max_length=20)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAppliances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_happ', models.CharField(choices=[('Refrigerator', 'Refrigerator'), ('TV', 'TV'), ('Washing_machine', 'Washing_machine'), ('Sofa', 'Sofa')], default='Refrigerator', max_length=20)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_sport', models.CharField(choices=[('Bicycle', 'Bicycle'), ('Treadmill', 'Treadmill'), ('Ball', 'Ball')], default='Bicycle', max_length=20)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Washing_machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('brand', models.CharField(choices=[('Bosch', 'Bosch'), ('Gplus', 'Gplus')], default='Bosch', max_length=20)),
                ('homeAppliances', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.HomeAppliances')),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('bluetooth', models.BooleanField()),
                ('brand', models.CharField(choices=[('LG', 'LG'), ('Samsung', 'Samsung')], default='LG', max_length=20)),
                ('homeAppliances', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.HomeAppliances')),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar', models.CharField(max_length=20)),
                ('clothes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Treadmill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_weight', models.IntegerField(default=0)),
                ('max_weight', models.IntegerField(default=0)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_st', models.CharField(choices=[('NoteBook', 'NoteBook'), ('Pen', 'Pen'), ('Crayons', 'Crayons'), ('Eraser', 'Eraser')], default='NoteBook', max_length=20)),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyMaterial', models.CharField(max_length=20)),
                ('coverMaterial', models.CharField(max_length=20)),
                ('homeAppliances', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.HomeAppliances')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve_height', models.CharField(choices=[('Short', 'Short'), ('Long', 'Long')], default='Short', max_length=20)),
                ('clothes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('deep', models.IntegerField(default=0)),
                ('brand', models.CharField(choices=[('Emersun', 'Emersun'), ('Snowa', 'Snowa')], default='Emersun', max_length=20)),
                ('homeAppliances', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.HomeAppliances')),
            ],
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('blue', 'blue'), ('black', 'black'), ('red', 'red')], default='blue', max_length=20)),
                ('stationery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Stationery')),
            ],
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('clothes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pages', models.IntegerField()),
                ('stationery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Stationery')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('color_this', models.CharField(choices=[('blue', 'blue'), ('black', 'black'), ('gray', 'gray'), ('brown', 'brown'), ('navy', 'navy')], default='blue', max_length=20)),
                ('electronic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Electronic')),
            ],
        ),
        migrations.CreateModel(
            name='Manto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_close', models.CharField(max_length=30)),
                ('belt', models.CharField(max_length=20)),
                ('clothes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LapTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(default=0)),
                ('ram', models.IntegerField(default=0)),
                ('color_this', models.CharField(choices=[('blue', 'blue'), ('black', 'black'), ('gray', 'gray'), ('brown', 'brown'), ('navy', 'navy')], default='blue', max_length=20)),
                ('electronic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Electronic')),
            ],
        ),
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(default='app/goods_image', max_length=200)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectionType', models.CharField(choices=[('wire', 'Wire'), ('wireless', 'Wireless')], default='wire', max_length=20)),
                ('led_indicator', models.BooleanField()),
                ('electronic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Electronic')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='interesting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Interesting'),
        ),
        migrations.CreateModel(
            name='Eraser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('stationery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Stationery')),
            ],
        ),
        migrations.AddField(
            model_name='electronic',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
        migrations.CreateModel(
            name='Crayons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('stationery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Stationery')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('not choice', 'not choice'), ('blue', 'blue'), ('black', 'black'), ('gray', 'gray'), ('brown', 'brown'), ('navy', 'navy')], default='not choice', max_length=20)),
                ('electronic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Electronic')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='good',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_num', models.IntegerField(default=0)),
                ('cable_type', models.CharField(choices=[('C', 'C Type'), ('Micro', 'Micro Type')], default='C', max_length=20)),
                ('electronic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Electronic')),
            ],
        ),
        migrations.CreateModel(
            name='Blouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collar', models.CharField(max_length=20)),
                ('clothes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Sport')),
            ],
        ),
    ]
