# Generated by Django 2.2.10 on 2020-10-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201012_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
            ],
        ),
    ]
