# Generated by Django 2.2.10 on 2020-10-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_code',
            name='code',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
