# Generated by Django 2.2.10 on 2020-10-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201015_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
        migrations.AlterField(
            model_name='interesting',
            name='good',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
    ]
