# Generated by Django 2.2.10 on 2020-10-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201022_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
