# Generated by Django 2.2.10 on 2020-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201022_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interesting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
