# Generated by Django 2.2.10 on 2020-10-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
        migrations.AlterField(
            model_name='interesting',
            name='good',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Good'),
        ),
    ]
