# Generated by Django 2.2.10 on 2020-10-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201022_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='color_choose',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobile',
            name='color_choose',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
