# Generated by Django 2.2.10 on 2020-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201023_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='size_this',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='size_this',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
