# Generated by Django 2.2.10 on 2020-10-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201023_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('no_size', 'no_size'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='L', max_length=10),
        ),
    ]
